### ISSUE TITLE
bug: Update profile for teacher (http://localhost:5173/teacher/profile/edit)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#312]
![image](https://github.com/user-attachments/assets/0e9731e6-3fc4-40cf-ba17-1440d412c979)

1. 
- Actual:
+ Nhập tên 'Đinh Quốc Lương' => Hiển thị lỗi ' Tên không hợp lệ! '
+ Nhập ngày sinh 01/01/2022 trở về sau => hiển thị lỗi 'Ngày sinh không hợp lệ!'

- Expected: 
+ Không hiển thị lỗi

2.
- actual: Ko update được ảnh 
- Expected: Update ảnh 

3.
- actual: cập nhật ngày sinh '10/02/2003' -> lưu
![image](https://github.com/user-attachments/assets/22a1f1d8-5b09-4e95-a272-70256d25cc22)

Database lưu ngày trước đó một ngày '09/02/2003' 
![image](https://github.com/user-attachments/assets/50264204-fb6f-4614-acad-ba9da51575af)

- expected: Lưu ngày chính xác

**Comment by htnghia1423** [comment]
@yuhtnguyen 
**Bug #3:** Because of the time zone difference, when updating the date of birth on the client, it is UTC +7, but when returning to the database, it will return to UTC, so it will be minus 7 hours. Dev has handled this by converting the date of birth in database back to UTC +7 for display.
**Note:** Should not log multiple bugs into the same issue. Recheck bug description format, follow template.

**Comment by yuhtnguyen** [comment]
@bakaqc  issue đã được sửa, nhưng xuất hiện bug khác, vui long follow [https://github.com/hardingadonis/ligevan/issues/370](url)
