### ISSUE TITLE
bug: update voucher (/admin/vouchers/671a2e5f75ae065934852b11/edit)

### ISSUE THREAD

**Issue by yuhtnguyen** [hardingadonis/ligevan#327]
1. Go to admin page
2. Go to voucher
3. Go to voucher detail
4. Click update voucher

actual:
![image](https://github.com/user-attachments/assets/1b9037a4-632e-46a2-832c-6548e1d62d0c)

expected:

fix lỗi trong ảnh

**Comment by htnghia1423** [comment]
Hi @yuhtnguyen,
**1. About Voucher Code field:** it will display as Read only (can't edit). So, user will not be able to edit at this field.
**2. About Discount percent field:** you fill with symbol "%" so it will have an error. And error message will display ass popup instead of error message under the field.
![image](https://github.com/user-attachments/assets/a00477c1-d2da-4c7a-b25d-f4c679c309c8)
**3. About displaying error message at Start date field:** the date you have logged bug is 2 days ago (28/10) and follow the rule that Voucher can only be created after the current date. So the value you fill (26/10) will have error.

Please help me to check it again.

Best regards,
NghiaHT

**Comment by yuhtnguyen** [comment]
Not bug - close
